name: proyecto_puzzlerace
description: Competitive puzzle racing mobile app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navegación
  go_router: ^13.2.0

  # Gestión de estado
  flutter_riverpod: ^2.5.1

  # Animaciones
  flutter_animate: ^4.5.0

  # Fuentes
  google_fonts: ^6.2.1

  # Íconos
  cupertino_icons: ^1.0.6

  # Persistencia local
  shared_preferences: ^2.2.3

  # Selección de imágenes del dispositivo
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/